function [] = R1_plot_fig6_7(SNR_in, SNR_out, sig_name)

% fig_R1_MR_cos
fname_RD1 = strcat('fig_R1_RD_f1_', sig_name);
fname_RD2 = strcat('fig_R1_RD_f2_', sig_name);
fname_MR = strcat('fig_R1_MR_', sig_name);
fname_LCR = strcat('fig_R1_MR_LCR_', sig_name);


%% fig var
B1 = [0 0.4470 0.7410];
B3 = [0.3010 0.7450 0.9330];
B2 = (B3 + B1)/2;

R_MB = [0.6350 0.0780 0.1840];
Y_Cl = [0.9290 0.6940 0.1250];

set(groot, 'defaultLegendInterpreter', 'latex');

%% fig 6 : RD
% Deux lignes
% 6 FIG : (f1, f2), (Signal x3 MCS)
% 5 courbes : (p = 10^(-2, -3, -4), MB RD, S RD)

figure;
hold on;
plot(SNR_in, SNR_out.RD.Cl(1, :), '-',...
    'Linewidth', 2,...
    'DisplayName', 'S-RD, $f_1$',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.RD.MB(1, :), '--',...
    'Linewidth', 2,...
    'DisplayName', 'MB-RD, $f_1$',...
    'Color', R_MB);
plot(SNR_in, SNR_out.RD.New(1, :, 1), '-*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_1$, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.RD.New(1, :, 2), '-s',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_1$, $\lambda = 10^{-5}$',...
    'Color', B2);
plot(SNR_in, SNR_out.RD.New(1, :, 3), '-o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_1$, $\lambda = 10^{-6}$',...
    'Color', B3);
hold off;
lgd = legend('Location', 'southeast');
lgd.FontSize = 24;
xlabel('SNR in', 'interpreter', 'latex');
ylabel('SNR out', 'interpreter', 'latex');
xAX = get(gca,'XAxis');
set(xAX,'FontSize', 26);
yAX = get(gca,'YAxis');
set(yAX,'FontSize', 26);
pbaspect([1 1 1]);
set(gcf, 'Position',  [0, 0, 1000, 1000])
savefig(fname_RD1);
saveas(gcf, fname_RD1, 'epsc');
close all

figure;
hold on;
plot(SNR_in, SNR_out.RD.Cl(2, :), '-',...
    'Linewidth', 2,...
    'DisplayName', 'S-RD, $f_2$',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.RD.MB(2, :), '--',...
    'Linewidth', 2,...
    'DisplayName', 'MB-RD, $f_2$',...
    'Color', R_MB);
plot(SNR_in, SNR_out.RD.New(2, :, 1), '-*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_2$, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.RD.New(2, :, 2), '-s',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_2$, $\lambda = 10^{-5}$',...
    'Color', B2);
plot(SNR_in, SNR_out.RD.New(2, :, 3), '-o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-RD, $f_2$, $\lambda = 10^{-6}$',...
    'Color', B3);
hold off;
lgd = legend('Location', 'southeast');
lgd.FontSize = 24;
xlabel('SNR in', 'interpreter', 'latex');
ylabel('SNR out', 'interpreter', 'latex');
xAX = get(gca,'XAxis');
set(xAX,'FontSize', 26);
yAX = get(gca,'YAxis');
set(yAX,'FontSize', 26);
pbaspect([1 1 1]);
set(gcf, 'Position',  [0, 0, 1000, 1000])
savefig(fname_RD2);
saveas(gcf, fname_RD2, 'epsc');
close all

%% fig 7 : MR LCR
% Deux lignes

% MR settings

ylim_v = [-2, 16];
yticks_v = -2:2:16;

% 3 FIG : MR 3 Sig MCS
% 8 Courbes : (f1, f2), (p_min, p_max, MB-MR, SR-MR)

figure;
subplot(2, 1, 1);
hold on;
plot(SNR_in, SNR_out.MR.Cl(1, :), '-',...
    'Linewidth', 2,...
    'DisplayName', 'S-MR',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.MR.MB(1, :), '--',...
    'Linewidth', 2,...
    'DisplayName', 'MB-MR',...
    'Color', R_MB);
plot(SNR_in, SNR_out.MR.New(1, :, 1), '-*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-MR, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.MR.New(1, :, 3), '-o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-MR, $\lambda = 10^{-6}$',...
    'Color', B3);
hold off;
ylim(ylim_v);
yticks(yticks_v);
lgd = legend('Location', 'southeast');
lgd.FontSize = 24;
xlabel('SNR in', 'interpreter', 'latex');
ylabel('SNR out', 'interpreter', 'latex');
xAX = get(gca,'XAxis');
set(xAX,'FontSize', 26);
yAX = get(gca,'YAxis');
set(yAX,'FontSize', 26);
% pbaspect([1 1 1]);

subplot(2, 1, 2);
hold on;
plot(SNR_in, SNR_out.MR.Cl(2, :), '-',...
    'Linewidth', 2,...
    'DisplayName', 'S-MR',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.MR.MB(2, :), '--',...
    'Linewidth', 2,...
    'DisplayName', 'MB-MR',...
    'Color', R_MB);
plot(SNR_in, SNR_out.MR.New(2, :, 1), '-*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-MR, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.MR.New(2, :, 3), '-o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-MR, $\lambda = 10^{-6}$',...
    'Color', B3);
hold off;
ylim(ylim_v);
yticks(yticks_v);
lgd = legend('Location', 'southeast');
lgd.FontSize = 24;
xlabel('SNR in', 'interpreter', 'latex');
ylabel('SNR out', 'interpreter', 'latex');
xAX = get(gca,'XAxis');
set(xAX,'FontSize', 26);
yAX = get(gca,'YAxis');
set(yAX,'FontSize', 26);
% pbaspect([1 1 1]);

set(gcf, 'Position',  [0, 0, 1000, 1000])
savefig(fname_MR);
saveas(gcf, fname_MR, 'epsc');
close all

% 3 FIG : LCR 3 Sig MCS
% 7 Courbes : (f1, f2), (smooth_p x3) + SR-MR-LCR

figure;
hold on;
plot(SNR_in, SNR_out.LCR.Cl(1, :), '-',...
    'Linewidth', 2,...
    'DisplayName', 'S-LCR-MR, $f_1$',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.LCR.New(1, :, 1), '-*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_1$, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.LCR.New(1, :, 2), '-s',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_1$, $\lambda = 10^{-5}$',...
    'Color', B2);
plot(SNR_in, SNR_out.LCR.New(1, :, 3), '-o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_1$, $\lambda = 10^{-6}$',...
    'Color', B3);
plot(SNR_in, SNR_out.LCR.Cl(2, :), '--',...
    'Linewidth', 2,...
    'DisplayName', 'S-LCR-MR, $f_2$',...
    'Color', Y_Cl);
plot(SNR_in, SNR_out.LCR.New(2, :, 1), '--*',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_2$, $\lambda = 10^{-4}$',...
    'Color', B1);
plot(SNR_in, SNR_out.LCR.New(2, :, 2), '--s',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_2$, $\lambda = 10^{-5}$',...
    'Color', B2);
plot(SNR_in, SNR_out.LCR.New(2, :, 3), '--o',...
    'Linewidth', 2, 'Markersize', 10,...
    'DisplayName', 'RRP-LCR-MR, $f_2$, $\lambda = 10^{-6}$',...
    'Color', B3);
hold off;
ylim(ylim_v);
yticks(yticks_v);
lgd = legend('Location', 'southeast');
lgd.FontSize = 24;
xlabel('SNR in', 'interpreter', 'latex');
ylabel('SNR out', 'interpreter', 'latex');
xAX = get(gca,'XAxis');
set(xAX,'FontSize', 26);
yAX = get(gca,'YAxis');
set(yAX,'FontSize', 26);
pbaspect([1 1 1]);
set(gcf, 'Position',  [0, 0, 1000, 1000])
savefig(fname_LCR);
saveas(gcf, fname_LCR, 'epsc');
close all

end

